apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-gcc5
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0071-tenant/tkrw-pr712-0075-0071-app/devfile-sample-gcc5@sha256:d4c0fbaffbc15a3c79551500243dc179ea295c35d680147901c948edfda654e6
        name: my-nodejs
        resources: {}
status: {}
